# HANDWRITTEN DIGIT RECOGNITION 

**In this project we will train our model to recognize and display the handwritten digits**

**We will be using CNN ARCHITECTURE here. -->
A CNN (Convolutional Neural Network) architecture in Python refers to a deep learning model structure designed for image and video recognition**

**We will be using LeNet 5 here. ---->LeNet-5 is one of the earliest and most well-known Convolutional Neural Network (CNN) architectures. 
---->Key Features of LeNet-5:---->
Designed for 28x28 grayscale images (like handwritten digits).->
Introduced convolution + pooling + fully connected layers. ->
Uses sigmoid/tanh activations (modern models often use ReLU). ->
Inspired modern deep learning architectures.**

**We will be using Mnist for digit datasets**

In [2]:
import pandas as pd
import numpy as np

In [8]:
pip install keras

In [10]:
pip install tensorflow

   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/376.0 MB 3.4 MB/s eta 0:01:52
   ---------------------------------------- 1.0/376.0 MB 3.3 MB/s eta 0:01:53
   ---------------------------------------- 1.8/376.0 MB 3.5 MB/s eta 0:01:48
   ---------------------------------------- 2.6/376.0 MB 3.4 MB/s eta 0:01:49
   ---------------------------------------- 3.4/376.0 MB 3.5 MB/s eta 0:01:48
   ---------------------------------------- 4.2/376.0 MB 3.5 MB/s eta 0:01:47
    --------------------------------------- 4.7/376.0 MB 3.5 MB/s eta 0:01:47
    --------------------------------------- 5.5/376.0 MB 3.5 MB/s eta 0:01:45
    --------------------------------------- 6.3/376.0 MB 3.5 MB/s eta 0:01:45
    --------------------------------------- 7.1/376.0 MB 3.6 MB/s eta 0:01:44
    --------------------------------------- 7.9/376.0 MB 3.5 MB/s eta 0:01:45
    --------------------------------------- 8.4/376.0 MB 3.5 MB/s eta 0

In [3]:
from tensorflow.keras import datasets   #The Keras library is used for building, training, and evaluating deep learning models

In [4]:
(x_train,y_train),(x_test,y_test)=datasets.mnist.load_data()

In [6]:
x_train  # This is the training data of numbers 

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [8]:
y_train # These are the labels of the training data i.e the 1st array value of x_train is of value 5 i.e mentioned in y_train(labels)

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

### Theory
**The data i.e the handwritten digits to be recognized (are in form of image) , as python does not undestand images thus needs
to be converted into actual numbers(digits) of a 3x3 matrix of array by encoding the data.**

**Thus the mnist dataset already has some preconverted dataset of numbers in a 3x3 array format, we are using this to train our model.**

In [9]:
x_train.shape

(60000, 28, 28)

In [10]:
x_test.shape

(10000, 28, 28)

**Thus we have 60000 images for our training and 10000 images for testing of length x width = 28x28**

**CNN will accept the data in 28 x 28 x 3 format , where 3 is RGB every image consists of red,blue,green channels.**

In [12]:
width,height = 28,28
input_shape = (width,height,1)

In [13]:
input_shape

(28, 28, 1)

### Now re schedule training data 

In [14]:
x_train = x_train.reshape(x_train.shape[0],height,width,1)
x_test = x_test.reshape(x_test.shape[0],height,width,1)

In [16]:
x_train.shape

(60000, 28, 28, 1)

In [17]:
x_test.shape

(10000, 28, 28, 1)

**So we have now re-scheduled...**
**Now we are using 1 here insted of 3 as 1 is used for gray scaling i.e black and white images as no red,green,blue channels are present in the dataset**

In [19]:
y_train.shape # It will not change as it has labels here only i.e the single numbers

(60000,)

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size =0.1 )

In [23]:
len(x_val)

6000

**In black and white images the range is between 0-255 so some images might have a value of 0(black) and some have value of 255(white) so
we need to Normalize our data by Feature Scaling so that our model will focus equally for all the images.**

In [26]:
## Normalizing Data
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

**We have Normalized our training data now we need to covert our testing data too...**

In [27]:
## Initial y_tarin ...
y_train

array([7, 5, 9, ..., 1, 1, 7], dtype=uint8)

In [28]:
from tensorflow import keras
num_labels=10
y_train=keras.utils.to_categorical(y_train)

In [29]:
# The modified data is now...
y_train

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [30]:
## Now for validation and testing data also ...
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

## Building Our Model

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout ,Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D
# Search for LeNet 5 Architecture to understand more

In [39]:
# Creating/Copying the architecture of LeNet 5 
model = Sequential()
model.add(Conv2D(6, kernel_size = (5, 5), strides = (1,1), activation = 'tanh', input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2) , strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1,1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2,2) , strides = (2,2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1,1), activation = 'tanh'))
## This is the feature Extractor Block that we havw done above 

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

**Let's see our model Layers Summary ...**

In [40]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_11 (Conv2D)                   │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_8                  │ (None, 23, 23, 6)           │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_12 (Conv2D)                   │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_9                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

**Now compiling our model ...**

In [42]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam' , metrics = ['accuracy'])

In [43]:
## Training Our model now ...
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9068 - loss: 0.3104 - val_accuracy: 0.9660 - val_loss: 0.1177
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9724 - loss: 0.0900 - val_accuracy: 0.9760 - val_loss: 0.0837
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9777 - loss: 0.0736 - val_accuracy: 0.9670 - val_loss: 0.1053
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9785 - loss: 0.0676 - val_accuracy: 0.9722 - val_loss: 0.0929
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9801 - loss: 0.0660 - val_accuracy: 0.9788 - val_loss: 0.0705
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9833 - loss: 0.0540 - val_accuracy: 0.9753 - val_loss: 0.0842
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9824 - loss: 0.0562 - val_accuracy: 0.9800 - val_loss: 0.0740
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9833 - loss: 0

### So Accuracy we got is 0.9889 & validation_accuracy we got is 0.0575

**In Neural Network the main objective here is to minimize the losses,
thus We are using loss function here which basically
take two values as input the y_pred value and the actual value and find based on that. ---->
We used 'categorical_crossentropy' as we are using multi class classification here. ----> Optimizer is used to fasten our process,
"Adam" is the fastest Optimizer. ---->in history we are training our model by providing our training data and labels here.**

**We are traing for 60000 datas which are being stored in gpu ram memory during execution but gpu ram is limited we cannot 
provide all at a time so we divide it into batches by using 'batch_size' function , here we are dividing the batch into 32 parts
, i.e 32 images will be prcessed at once .**

### Testing our data 

In [44]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9851 - loss: 0.0452


In [45]:
score

[0.037847381085157394, 0.9882000088691711]

### Training Accuracy we got = 0.9882...